<?php

namespace AppBundle\Repository;

/**
 * FosUserLoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FosUserLoginRepository extends \Doctrine\ORM\EntityRepository
{
}
