<?php

namespace AppBundle\Repository;

/**
 * NewProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewProductRepository extends \Doctrine\ORM\EntityRepository
{
}
