# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

            remember_me:
              secret: '%secret%'
              lifetime: 60480
              path:   /
              domain: ~
              user_provider: fos_userbundle

    access_control:
        - { path: ^/$, roles: [IS_AUTHENTICATED_REMEMBERED,  IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/register/confirmed, roles: [IS_AUTHENTICATED_REMEMBERED,  IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/login$, allow_if:  "is_anonymous() and !is_authenticated()" }
        - { path: ^/register, allow_if:  "is_anonymous() and !is_authenticated()" }
        - { path: ^/resetting,  allow_if:  "is_anonymous() and !is_authenticated()" }
        - { path: ^/admin, role: ROLE_ADMIN }