<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

$this->services['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$a = new \Symfony\Component\ExpressionLanguage\SerializedParsedExpression('is_anonymous() and !is_authenticated()', 'O:52:"Symfony\\Component\\ExpressionLanguage\\Node\\BinaryNode":2:{s:5:"nodes";a:2:{s:4:"left";O:54:"Symfony\\Component\\ExpressionLanguage\\Node\\FunctionNode":2:{s:5:"nodes";a:1:{s:9:"arguments";O:46:"Symfony\\Component\\ExpressionLanguage\\Node\\Node":2:{s:5:"nodes";a:0:{}s:10:"attributes";a:0:{}}}s:10:"attributes";a:1:{s:4:"name";s:12:"is_anonymous";}}s:5:"right";O:51:"Symfony\\Component\\ExpressionLanguage\\Node\\UnaryNode":2:{s:5:"nodes";a:1:{s:4:"node";O:54:"Symfony\\Component\\ExpressionLanguage\\Node\\FunctionNode":2:{s:5:"nodes";a:1:{s:9:"arguments";O:46:"Symfony\\Component\\ExpressionLanguage\\Node\\Node":2:{s:5:"nodes";a:0:{}s:10:"attributes";a:0:{}}}s:10:"attributes";a:1:{s:4:"name";s:16:"is_authenticated";}}}s:10:"attributes";a:1:{s:8:"operator";s:1:"!";}}}s:10:"attributes";a:1:{s:8:"operator";s:3:"and";}}');

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/$'), array(0 => 'IS_AUTHENTICATED_REMEMBERED', 1 => 'IS_AUTHENTICATED_ANONYMOUSLY'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/register/confirmed'), array(0 => 'IS_AUTHENTICATED_REMEMBERED', 1 => 'IS_AUTHENTICATED_ANONYMOUSLY'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/login$'), array(0 => $a), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/register'), array(0 => $a), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/resetting'), array(0 => $a), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin'), array(0 => 'ROLE_ADMIN'), NULL);

return $instance;
