<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA2bxmtx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA2bxmtx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerA2bxmtx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerA2bxmtx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerA2bxmtx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'A2bxmtx',
    'container.build_id' => '58731fc8',
    'container.build_time' => 1517425977,
));
