<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNeze2bf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNeze2bf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNeze2bf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNeze2bf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNeze2bf\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Neze2bf',
    'container.build_id' => '8817e4e2',
    'container.build_time' => 1521472289,
));
