<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDr4xl7v\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDr4xl7v/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDr4xl7v.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDr4xl7v\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDr4xl7v\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Dr4xl7v',
    'container.build_id' => '0b7f7aec',
    'container.build_time' => 1521468668,
));
